-- MySQL Script generated by MySQL Workbench
-- Tue 05 May 2020 05:40:11 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campus` (
                                               `Campus_ID` VARCHAR(50) NOT NULL,
                                               `Campus_Name` VARCHAR(50) NOT NULL,
                                               `Campus_Address` VARCHAR(200) NULL,
                                               PRIMARY KEY (`Campus_ID`),
                                               UNIQUE INDEX `Campus_ID_UNIQUE` (`Campus_ID` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
                                                   `Department_ID` VARCHAR(50) NOT NULL,
                                                   `Department_Name` VARCHAR(50) NULL,
                                                   `Department_Address` VARCHAR(200) NULL,
                                                   `Department_Dean` VARCHAR(50) NULL,
                                                   `Department_Campus_ID` VARCHAR(50) NOT NULL,
                                                   PRIMARY KEY (`Department_ID`),
                                                   UNIQUE INDEX `Department_ID_UNIQUE` (`Department_ID` ASC) VISIBLE,
                                                   INDEX `fk_Department_Campus_idx` (`Department_Campus_ID` ASC) VISIBLE,
                                                   UNIQUE INDEX `Campus_Campus_ID_UNIQUE` (`Department_Campus_ID` ASC) VISIBLE,
                                                   CONSTRAINT `fk_Department_Campus`
                                                       FOREIGN KEY (`Department_Campus_ID`)
                                                           REFERENCES `mydb`.`Campus` (`Campus_ID`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
                                                `Teacher_ID` VARCHAR(50) NOT NULL,
                                                `Teacher_Enroll_Date` DATE NOT NULL,
                                                `Teacher_Department_ID` VARCHAR(50) NULL,
                                                `Teacher_Title` VARCHAR(45) NULL,
                                                PRIMARY KEY (`Teacher_ID`),
                                                UNIQUE INDEX `Teacher_ID_UNIQUE` (`Teacher_ID` ASC) VISIBLE,
                                                INDEX `fk_Teacher_Department1_idx` (`Teacher_Department_ID` ASC) VISIBLE,
                                                CONSTRAINT `fk_Teacher_Department1`
                                                    FOREIGN KEY (`Teacher_Department_ID`)
                                                        REFERENCES `mydb`.`Department` (`Department_ID`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
                                              `Class_ID` VARCHAR(50) NOT NULL,
                                              `Class_Name` VARCHAR(45) NOT NULL,
                                              `Class_Date` DATE NOT NULL,
                                              `Class_Grade` VARCHAR(45) NOT NULL,
                                              `Class_Department_ID` VARCHAR(50) NOT NULL,
                                              `Class_Head_Teacher_ID` VARCHAR(50) NOT NULL,
                                              PRIMARY KEY (`Class_ID`),
                                              UNIQUE INDEX `Class_ID_UNIQUE` (`Class_ID` ASC) VISIBLE,
                                              INDEX `fk_Class_Department1_idx` (`Class_Department_ID` ASC) VISIBLE,
                                              INDEX `fk_Class_Teacher1_idx` (`Class_Head_Teacher_ID` ASC) VISIBLE,
                                              CONSTRAINT `fk_Class_Department1`
                                                  FOREIGN KEY (`Class_Department_ID`)
                                                      REFERENCES `mydb`.`Department` (`Department_ID`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                              CONSTRAINT `fk_Class_Teacher1`
                                                  FOREIGN KEY (`Class_Head_Teacher_ID`)
                                                      REFERENCES `mydb`.`Teacher` (`Teacher_ID`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB
    COMMENT = '																						';


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
                                               `ID_Card_Number` VARCHAR(50) NOT NULL,
                                               `ID_Card_Type` TINYINT NOT NULL DEFAULT 0,
                                               `Name` VARCHAR(45) CHARACTER SET 'utf16' NOT NULL,
                                               `Gender` TINYINT NOT NULL,
                                               `Birth` DATE NOT NULL,
                                               `Nationality` VARCHAR(45) CHARACTER SET 'utf16' NOT NULL,
                                               `Address` VARCHAR(45) NULL,
                                               `Address_ID` VARCHAR(45) NULL,
                                               `Address_Phone_Number` VARCHAR(45) NULL,
                                               PRIMARY KEY (`ID_Card_Number`),
                                               UNIQUE INDEX `ID_Card_Number_UNIQUE` (`ID_Card_Number` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
                                                    `Transaction_ID` VARCHAR(50) NOT NULL,
                                                    `Transaction_Type` TINYINT NOT NULL,
                                                    `Transaction_Date` DATE NOT NULL,
                                                    `Transaction_Origin_Class_ID` VARCHAR(50) NOT NULL,
                                                    `Transaction_Current_Class_ID` VARCHAR(50) NOT NULL,
                                                    `Transaction_League_Member` VARCHAR(45) NOT NULL,
                                                    `Transaction_Reason` TINYINT NOT NULL,
                                                    PRIMARY KEY (`Transaction_ID`),
                                                    INDEX `fk_Transaction_Class1_idx` (`Transaction_Origin_Class_ID` ASC) VISIBLE,
                                                    INDEX `fk_Transaction_Class2_idx` (`Transaction_Current_Class_ID` ASC) VISIBLE,
                                                    CONSTRAINT `fk_Transaction_Class1`
                                                        FOREIGN KEY (`Transaction_Origin_Class_ID`)
                                                            REFERENCES `mydb`.`Class` (`Class_ID`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION,
                                                    CONSTRAINT `fk_Transaction_Class2`
                                                        FOREIGN KEY (`Transaction_Current_Class_ID`)
                                                            REFERENCES `mydb`.`Class` (`Class_ID`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
                                                `Student_ID` VARCHAR(50) NOT NULL,
                                                `Student_Enroll_Date` DATE NOT NULL,
                                                `Stuent_Email` VARCHAR(45) NOT NULL,
                                                `Student_Class_ID` VARCHAR(50) NOT NULL,
                                                `Student_Transaction_ID` VARCHAR(50) NOT NULL,
                                                PRIMARY KEY (`Student_ID`),
                                                INDEX `fk_Student_Class1_idx` (`Student_Class_ID` ASC) VISIBLE,
                                                UNIQUE INDEX `Student_ID_UNIQUE` (`Student_ID` ASC) VISIBLE,
                                                INDEX `fk_Student_Transaction1_idx` (`Student_Transaction_ID` ASC) VISIBLE,
                                                CONSTRAINT `fk_Student_Class1`
                                                    FOREIGN KEY (`Student_Class_ID`)
                                                        REFERENCES `mydb`.`Class` (`Class_ID`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_Student_Transaction1`
                                                    FOREIGN KEY (`Student_Transaction_ID`)
                                                        REFERENCES `mydb`.`Transaction` (`Transaction_ID`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_Identity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_Identity` (
                                                         `Student_Student_ID` VARCHAR(50) NOT NULL,
                                                         `Person_ID_Card_Number` VARCHAR(50) NOT NULL,
                                                         PRIMARY KEY (`Student_Student_ID`),
                                                         INDEX `fk_table1_Student1_idx` (`Student_Student_ID` ASC) VISIBLE,
                                                         INDEX `fk_table1_Person1_idx` (`Person_ID_Card_Number` ASC) VISIBLE,
                                                         UNIQUE INDEX `Student_Student_ID_UNIQUE` (`Student_Student_ID` ASC) VISIBLE,
                                                         UNIQUE INDEX `Person_ID_Card_Number_UNIQUE` (`Person_ID_Card_Number` ASC) VISIBLE,
                                                         CONSTRAINT `fk_table1_Student1`
                                                             FOREIGN KEY (`Student_Student_ID`)
                                                                 REFERENCES `mydb`.`Student` (`Student_ID`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION,
                                                         CONSTRAINT `fk_table1_Person1`
                                                             FOREIGN KEY (`Person_ID_Card_Number`)
                                                                 REFERENCES `mydb`.`Person` (`ID_Card_Number`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher_Identity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher_Identity` (
                                                         `Teacher_Teacher_ID` VARCHAR(50) NOT NULL,
                                                         `Person_ID_Card_Number` VARCHAR(50) NOT NULL,
                                                         INDEX `fk_Teacher_Identity_Teacher1_idx` (`Teacher_Teacher_ID` ASC) VISIBLE,
                                                         INDEX `fk_Teacher_Identity_Person1_idx` (`Person_ID_Card_Number` ASC) VISIBLE,
                                                         PRIMARY KEY (`Teacher_Teacher_ID`),
                                                         UNIQUE INDEX `Teacher_Teacher_ID_UNIQUE` (`Teacher_Teacher_ID` ASC) VISIBLE,
                                                         UNIQUE INDEX `Person_ID_Card_Number_UNIQUE` (`Person_ID_Card_Number` ASC) VISIBLE,
                                                         CONSTRAINT `fk_Teacher_Identity_Teacher1`
                                                             FOREIGN KEY (`Teacher_Teacher_ID`)
                                                                 REFERENCES `mydb`.`Teacher` (`Teacher_ID`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION,
                                                         CONSTRAINT `fk_Teacher_Identity_Person1`
                                                             FOREIGN KEY (`Person_ID_Card_Number`)
                                                                 REFERENCES `mydb`.`Person` (`ID_Card_Number`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
                                               `Course_ID` VARCHAR(50) NOT NULL,
                                               `Course_Name` VARCHAR(50) NOT NULL,
                                               `Course_Department_ID` VARCHAR(50) NOT NULL,
                                               `Course_Teacher_ID` VARCHAR(50) NOT NULL,
                                               `Course_Exam_Type` VARCHAR(45) NULL,
                                               `Course_Semester` VARCHAR(45) NULL,
                                               `Course_Year` VARCHAR(45) NULL,
                                               `Course_Time` VARCHAR(45) NULL,
                                               PRIMARY KEY (`Course_ID`),
                                               INDEX `fk_Course_Department1_idx` (`Course_Department_ID` ASC) VISIBLE,
                                               INDEX `fk_Course_Teacher1_idx` (`Course_Teacher_ID` ASC) VISIBLE,
                                               UNIQUE INDEX `Course_ID_UNIQUE` (`Course_ID` ASC) VISIBLE,
                                               CONSTRAINT `fk_Course_Department1`
                                                   FOREIGN KEY (`Course_Department_ID`)
                                                       REFERENCES `mydb`.`Department` (`Department_ID`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION,
                                               CONSTRAINT `fk_Course_Teacher1`
                                                   FOREIGN KEY (`Course_Teacher_ID`)
                                                       REFERENCES `mydb`.`Teacher` (`Teacher_ID`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CourseSelection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CourseSelection` (
                                                        `CourseSelection_ID` INT NOT NULL AUTO_INCREMENT,
                                                        `CourseSelection_Course_ID` VARCHAR(50) NOT NULL,
                                                        `CourseSelection_Student_ID` VARCHAR(50) NOT NULL,
                                                        `CourseSelection_Date` VARCHAR(45) NULL,
                                                        `CourseSelection_Semester` VARCHAR(45) NULL,
                                                        `Score` INT NULL,
                                                        INDEX `fk_CourseSelection_Student1_idx` (`CourseSelection_Student_ID` ASC) VISIBLE,
                                                        PRIMARY KEY (`CourseSelection_ID`),
                                                        INDEX `fk_CourseSelection_Course1_idx` (`CourseSelection_Course_ID` ASC) VISIBLE,
                                                        CONSTRAINT `fk_CourseSelection_Student1`
                                                            FOREIGN KEY (`CourseSelection_Student_ID`)
                                                                REFERENCES `mydb`.`Student` (`Student_ID`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_CourseSelection_Course1`
                                                            FOREIGN KEY (`CourseSelection_Course_ID`)
                                                                REFERENCES `mydb`.`Course` (`Course_ID`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
                                             `id` INT NOT NULL AUTO_INCREMENT,
                                             `username` VARCHAR(45) NOT NULL,
                                             `password` VARCHAR(45) NOT NULL,
                                             `usertype` INT NOT NULL,
                                             `foreign_id` VARCHAR(45) NULL,
                                             PRIMARY KEY (`id`),
                                             UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                             UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
    ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Student_BEFORE_UPDATE` BEFORE UPDATE ON `Student` FOR EACH ROW
BEGIN
    IF NOT OLD.Student_Transaction_ID = NULL THEN
        SIGNAL SQLSTATE '01000'
            SET MESSAGE_TEXT = 'This Student Has Transaction Before', MYSQL_ERRNO = 1000;
    END IF;
END;$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`CourseSelection_BEFORE_INSERT` BEFORE INSERT ON `CourseSelection` FOR EACH ROW
BEGIN
    SET NEW.CourseSelection_Date =
            (SELECT CourseSelection_Date FROM Course WHERE Course.Course_ID = NEW.CourseSelection_ID);
    SET NEW.CourseSelection_Semester =
            (SELECT CourseSelection_Semester FROM Course WHERE Course.Course_ID = NEW.CourseSelection_ID);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
