all:
	xelatex -synctex=1 -interaction=nonstopmode "report".tex

cleanall:
	rm -f report.pdf
	rm -f report.aux report.bbl report.blg report.log report.out report.synctex.gz report.toc

cleancache:
	rm -f report.aux report.bbl report.blg report.log report.out report.synctex.gz report.toc
